# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(725, 538)
        Dialog.setStyleSheet("QDialog{\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.0113636 rgba(73, 9, 87, 255), stop:0.244318 rgba(59, 25, 105, 255), stop:0.431818 rgba(52, 35, 115, 255), stop:0.744318 rgba(20, 48, 116, 255), stop:0.982955 rgba(13, 53, 125, 255));\n"
"}\n"
"")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(260, 20, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setStyleSheet("color: qlineargradient(spread:repeat, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(89, 16, 118, 255));")
        self.title.setObjectName("title")
        self.temperaturelabel = QtWidgets.QLabel(Dialog)
        self.temperaturelabel.setGeometry(QtCore.QRect(50, 120, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.temperaturelabel.setFont(font)
        self.temperaturelabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.temperaturelabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.temperaturelabel.setObjectName("temperaturelabel")
        self.location = QtWidgets.QLabel(Dialog)
        self.location.setGeometry(QtCore.QRect(430, 190, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.location.setFont(font)
        self.location.setStyleSheet("color: rgb(255, 255, 255);")
        self.location.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.location.setObjectName("location")
        self.imgpath = QtWidgets.QLabel(Dialog)
        self.imgpath.setGeometry(QtCore.QRect(60, 190, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.imgpath.setFont(font)
        self.imgpath.setStyleSheet("color: rgb(255, 255, 255);")
        self.imgpath.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imgpath.setObjectName("imgpath")
        self.filenamelbl = QtWidgets.QLabel(Dialog)
        self.filenamelbl.setGeometry(QtCore.QRect(80, 260, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.filenamelbl.setFont(font)
        self.filenamelbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.filenamelbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.filenamelbl.setObjectName("filenamelbl")
        self.outputpathlbl = QtWidgets.QLabel(Dialog)
        self.outputpathlbl.setGeometry(QtCore.QRect(50, 340, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.outputpathlbl.setFont(font)
        self.outputpathlbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.outputpathlbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.outputpathlbl.setObjectName("outputpathlbl")
        self.outputfilenamelbl1 = QtWidgets.QLabel(Dialog)
        self.outputfilenamelbl1.setGeometry(QtCore.QRect(70, 420, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.outputfilenamelbl1.setFont(font)
        self.outputfilenamelbl1.setStyleSheet("color: rgb(255, 255, 255);")
        self.outputfilenamelbl1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.outputfilenamelbl1.setObjectName("outputfilenamelbl1")
        self.fileforamtlbl = QtWidgets.QLabel(Dialog)
        self.fileforamtlbl.setGeometry(QtCore.QRect(390, 270, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fileforamtlbl.setFont(font)
        self.fileforamtlbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.fileforamtlbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fileforamtlbl.setObjectName("fileforamtlbl")
        self.temperature = QtWidgets.QTextBrowser(Dialog)
        self.temperature.setGeometry(QtCore.QRect(170, 130, 201, 41))
        self.temperature.setObjectName("temperature")
        self.i = QtWidgets.QTextBrowser(Dialog)
        self.i.setGeometry(QtCore.QRect(530, 200, 71, 41))
        self.i.setObjectName("i")
        self.j = QtWidgets.QTextBrowser(Dialog)
        self.j.setGeometry(QtCore.QRect(630, 200, 71, 41))
        self.j.setObjectName("j")
        self.imagepath = QtWidgets.QTextBrowser(Dialog)
        self.imagepath.setGeometry(QtCore.QRect(170, 200, 201, 41))
        self.imagepath.setObjectName("imagepath")
        self.filename = QtWidgets.QTextBrowser(Dialog)
        self.filename.setGeometry(QtCore.QRect(170, 270, 201, 41))
        self.filename.setObjectName("filename")
        self.fileformat = QtWidgets.QTextBrowser(Dialog)
        self.fileformat.setGeometry(QtCore.QRect(500, 270, 201, 41))
        self.fileformat.setObjectName("fileformat")
        self.outputpath = QtWidgets.QTextBrowser(Dialog)
        self.outputpath.setGeometry(QtCore.QRect(170, 340, 201, 41))
        self.outputpath.setObjectName("outputpath")
        self.outputfilenamelbl = QtWidgets.QLabel(Dialog)
        self.outputfilenamelbl.setGeometry(QtCore.QRect(80, 390, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.outputfilenamelbl.setFont(font)
        self.outputfilenamelbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.outputfilenamelbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.outputfilenamelbl.setObjectName("outputfilenamelbl")
        self.outputfilename = QtWidgets.QTextBrowser(Dialog)
        self.outputfilename.setGeometry(QtCore.QRect(170, 410, 201, 41))
        self.outputfilename.setObjectName("outputfilename")
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(450, 400, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ok.setFont(font)
        self.ok.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0.438, y1:0, x2:0.437, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(162, 162, 162, 255));\n"
"color: rgb(99, 99, 99);")
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(590, 400, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0.438, y1:0, x2:0.437, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(162, 162, 162, 255));\n"
"color: rgb(99, 99, 99);")
        self.cancel.setObjectName("cancel")
        self.eyphen = QtWidgets.QLabel(Dialog)
        self.eyphen.setGeometry(QtCore.QRect(610, 190, 41, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.eyphen.setFont(font)
        self.eyphen.setStyleSheet("color: rgb(255, 255, 255);")
        self.eyphen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.eyphen.setObjectName("eyphen")
        self.celsius = QtWidgets.QRadioButton(Dialog)
        self.celsius.setGeometry(QtCore.QRect(440, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.celsius.setFont(font)
        self.celsius.setStyleSheet("color: rgb(255, 255, 255);")
        self.celsius.setObjectName("celsius")
        self.fahrenheit = QtWidgets.QRadioButton(Dialog)
        self.fahrenheit.setGeometry(QtCore.QRect(560, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fahrenheit.setFont(font)
        self.fahrenheit.setStyleSheet("color: rgb(255, 255, 255);")
        self.fahrenheit.setObjectName("fahrenheit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "ENCRYPTION"))
        self.temperaturelabel.setText(_translate("Dialog", "Temperature:"))
        self.location.setText(_translate("Dialog", "Location:"))
        self.imgpath.setText(_translate("Dialog", "Image path:"))
        self.filenamelbl.setText(_translate("Dialog", "Filename:"))
        self.outputpathlbl.setText(_translate("Dialog", "Output path:"))
        self.outputfilenamelbl1.setText(_translate("Dialog", "Filename:"))
        self.fileforamtlbl.setText(_translate("Dialog", "File Format:"))
        self.outputfilenamelbl.setText(_translate("Dialog", "Output"))
        self.ok.setText(_translate("Dialog", "OK"))
        self.cancel.setText(_translate("Dialog", "Exit"))
        self.eyphen.setText(_translate("Dialog", "-"))
        self.celsius.setText(_translate("Dialog", "Celsius"))
        self.fahrenheit.setText(_translate("Dialog", "Fahrenheit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

